name: bashtest

on: [push]

jobs:
  bashtest:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, 'no-workflow')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: Run bash tests
        env:
          WEBDAV_HOSTNAME: ${{ secrets.WEBDAV_HOSTNAME }}
          WEBDAV_LOGIN: ${{ secrets.WEBDAV_LOGIN }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
          S3_STORAGE_ENDPOINT_URL: ${{ secrets.S3_STORAGE_ENDPOINT_URL }}
          S3_STORAGE_AWS_ACCESS_KEY_ID: ${{ secrets.S3_STORAGE_AWS_ACCESS_KEY_ID }}
          S3_STORAGE_AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_STORAGE_AWS_SECRET_ACCESS_KEY }}
          BLUER_AGENT_API_KEY: ${{ secrets.BLUER_AGENT_API_KEY }}
          BLUER_AGENT_CHAT_ENDPOINT: ${{ secrets.BLUER_AGENT_CHAT_ENDPOINT }}
          BLUER_AGENT_EMBEDDING_ENDPOINT: ${{ secrets.BLUER_AGENT_EMBEDDING_ENDPOINT }}
          BLUER_AGENT_TRANSCRIPTION_ENDPOINT: ${{ secrets.BLUER_AGENT_TRANSCRIPTION_ENDPOINT }}
          BLUER_AGENT_VOICE_ENDPOINT: ${{ secrets.BLUER_AGENT_VOICE_ENDPOINT }}
          BLUER_AGENT_VOICE_TOKEN: ${{ secrets.BLUER_AGENT_VOICE_TOKEN }}

        run: |
          echo "WEBDAV_HOSTNAME: $WEBDAV_HOSTNAME"
          echo "WEBDAV_LOGIN: $WEBDAV_LOGIN"
          echo "WEBDAV_PASSWORD: $WEBDAV_PASSWORD"
          echo "S3_STORAGE_ENDPOINT_URL: $S3_STORAGE_ENDPOINT_URL"
          echo "S3_STORAGE_AWS_ACCESS_KEY_ID: $S3_STORAGE_AWS_ACCESS_KEY_ID"
          echo "S3_STORAGE_AWS_SECRET_ACCESS_KEY: $S3_STORAGE_AWS_SECRET_ACCESS_KEY"
          echo "BLUER_AGENT_API_KEY: $BLUER_AGENT_API_KEY"
          echo "BLUER_AGENT_CHAT_ENDPOINT: $BLUER_AGENT_CHAT_ENDPOINT"
          echo "BLUER_AGENT_EMBEDDING_ENDPOINT: $BLUER_AGENT_EMBEDDING_ENDPOINT"
          echo "BLUER_AGENT_TRANSCRIPTION_ENDPOINT: $BLUER_AGENT_TRANSCRIPTION_ENDPOINT"
          echo "BLUER_AGENT_VOICE_ENDPOINT: $BLUER_AGENT_VOICE_ENDPOINT"
          echo "BLUER_AGENT_VOICE_TOKEN: $BLUER_AGENT_VOICE_TOKEN"

          ./.github/workflows/bashtest.sh bluer_agent
